# single perceptron

In [1]:
import torch #importing torch for using pytorch 

In [2]:
#using sigmoid activation function for squashing the output of neural networks between 0-1 as a probability.
def activation(x): 
    return 1/(1+torch.exp(-x)) 

In [3]:
torch.manual_seed(7) #to make sure that random numbers picked are same during each execution of program

features=torch.randn((1,5)) #picking random numbers from normal distribution that is a distribution which has mean 0 and stdeviation 1 of dimensions 1 row and 5 columns
weights=torch.randn_like(features) #making sure that weight has same shape (dimensions) as features that is 1 row and 5 columns
bias=torch.randn((1,1)) #making sure that bias is a tensor of dimensions 1 row and 1 columns so basically 1 value
weights=weights.view(5,1) #weights change as 5 row and 1 columns so , that multiplication capability is checked 
print(weights) #printing weights tensors
print(features) #printing features tensors
print(activation(torch.mm(features,weights)+bias)) #printing final outputs


tensor([[-0.8948],
        [-0.3556],
        [ 1.2324],
        [ 0.1382],
        [-1.6822]])
tensor([[-0.1468,  0.7861,  0.9468, -1.1143,  1.6908]])
tensor([[0.1595]])


# multilayer perceptron

In [4]:
torch.manual_seed(7)

# Features are 3 random normal variables
features = torch.randn((1, 3))
# Define the size of each layer in our network
n_input = features.shape[1]     # Number of input units, must match number of input features
n_hidden = 2                    # Number of hidden units 
n_output = 1                    # Number of output units

# Weights for inputs to hidden layer it genralizes to torch.randn(layer_before_it_units,current_layer_units)
W1 = torch.randn(n_input, n_hidden)
# Weights for hidden layer to output layer
W2 = torch.randn(n_hidden, n_output)

# and bias terms for hidden and output layers
B1 = torch.randn((1, n_hidden))
B2 = torch.randn((1, n_output))

h=activation(torch.mm(features,W1)+B1)
o=activation(torch.mm(h,W2)+B2)

print(W1)
print(W2)
print(B1)
print(B2)
print(h)
print(o)


tensor([[-1.1143,  1.6908],
        [-0.8948, -0.3556],
        [ 1.2324,  0.1382]])
tensor([[-1.6822],
        [ 0.3177]])
tensor([[0.1328, 0.1373]])
tensor([[0.2405]])
tensor([[0.6813, 0.4355]])
tensor([[0.3171]])


# numpy and pytorch

In [5]:
import numpy as np

In [6]:
a=np.random.rand(4,3) #creating a random array of dimensions - 4 rows and 3 columns 
a

array([[0.38462246, 0.80409084, 0.04258804],
       [0.08319516, 0.38643379, 0.79375325],
       [0.59954652, 0.60869509, 0.01011964],
       [0.3461263 , 0.79690306, 0.21441207]])

In [7]:
b=torch.from_numpy(a) #creating a pytorch tensor from numpy array
b

tensor([[0.3846, 0.8041, 0.0426],
        [0.0832, 0.3864, 0.7938],
        [0.5995, 0.6087, 0.0101],
        [0.3461, 0.7969, 0.2144]], dtype=torch.float64)

In [8]:
c=b.numpy() #converting our tensor back to numpy
c

array([[0.38462246, 0.80409084, 0.04258804],
       [0.08319516, 0.38643379, 0.79375325],
       [0.59954652, 0.60869509, 0.01011964],
       [0.3461263 , 0.79690306, 0.21441207]])

In [9]:
d=b.mul_(2) #multiplying our tensor by 2 to see corresponding change in our numpy array
d

tensor([[0.7692, 1.6082, 0.0852],
        [0.1664, 0.7729, 1.5875],
        [1.1991, 1.2174, 0.0202],
        [0.6923, 1.5938, 0.4288]], dtype=torch.float64)

In [10]:
c # shows numpy arrays also change with changes made in pytorch tensors.

array([[0.76924492, 1.60818168, 0.08517608],
       [0.16639032, 0.77286757, 1.5875065 ],
       [1.19909304, 1.21739018, 0.02023929],
       [0.69225261, 1.59380613, 0.42882414]])