# single perceptron

In [5]:
import torch #importing torch for using pytorch 

In [6]:
#using sigmoid activation function for squashing the output of neural networks between 0-1 as a probability.
def activation(x): 
    return 1/(1+torch.exp(-x)) 

In [7]:
torch.manual_seed(7) #to make sure that random numbers picked are same during each execution of program

features=torch.randn((1,5)) #picking random numbers from normal distribution that is a distribution which has mean 0 and stdeviation 1 of dimensions 1 row and 5 columns
weights=torch.randn_like(features) #making sure that weight has same shape (dimensions) as features that is 1 row and 5 columns
bias=torch.randn((1,1)) #making sure that bias is a tensor of dimensions 1 row and 1 columns so basically 1 value
weights=weights.view(5,1) #weights change as 5 row and 1 columns so , that multiplication capability is checked 
print(weights) #printing weights tensors
print(features) #printing features tensors
print(activation(torch.mm(features,weights)+bias)) #printing final outputs


tensor([[-0.8948],
        [-0.3556],
        [ 1.2324],
        [ 0.1382],
        [-1.6822]])
tensor([[-0.1468,  0.7861,  0.9468, -1.1143,  1.6908]])
tensor([[0.1595]])


# multilayer perceptron

In [16]:
torch.manual_seed(7)

# Features are 3 random normal variables
features = torch.randn((1, 3))
# Define the size of each layer in our network
n_input = features.shape[1]     # Number of input units, must match number of input features
n_hidden = 2                    # Number of hidden units 
n_output = 1                    # Number of output units

# Weights for inputs to hidden layer it genralizes to torch.randn(layer_before_it_units,current_layer_units)
W1 = torch.randn(n_input, n_hidden)
# Weights for hidden layer to output layer
W2 = torch.randn(n_hidden, n_output)

# and bias terms for hidden and output layers
B1 = torch.randn((1, n_hidden))
B2 = torch.randn((1, n_output))

h=activation(torch.mm(features,W1)+B1)
o=activation(torch.mm(h,W2)+B2)

print(o)


tensor([[0.3171]])


# numpy and pytorch

In [17]:
import numpy as np

In [20]:
a=np.random.rand(4,3) #creating a random array of dimensions - 4 rows and 3 columns 
a

array([[0.87891112, 0.18103495, 0.15642454],
       [0.82746325, 0.49493963, 0.23733886],
       [0.60682896, 0.18754307, 0.30518316],
       [0.46101847, 0.90824038, 0.6861644 ]])

In [21]:
b=torch.from_numpy(a) #creating a pytorch tensor from numpy array
b

tensor([[0.8789, 0.1810, 0.1564],
        [0.8275, 0.4949, 0.2373],
        [0.6068, 0.1875, 0.3052],
        [0.4610, 0.9082, 0.6862]], dtype=torch.float64)

In [23]:
c=b.numpy() #converting our tensor back to numpy
c

array([[0.87891112, 0.18103495, 0.15642454],
       [0.82746325, 0.49493963, 0.23733886],
       [0.60682896, 0.18754307, 0.30518316],
       [0.46101847, 0.90824038, 0.6861644 ]])

In [25]:
d=b.mul_(2) #multiplying our tensor by 2 to see corresponding change in our numpy array
d

tensor([[3.5156, 0.7241, 0.6257],
        [3.3099, 1.9798, 0.9494],
        [2.4273, 0.7502, 1.2207],
        [1.8441, 3.6330, 2.7447]], dtype=torch.float64)

In [26]:
c # shows numpy arrays also change with changes made in pytorch tensors.

array([[3.51564449, 0.72413981, 0.62569814],
       [3.30985301, 1.97975853, 0.94935542],
       [2.42731585, 0.75017228, 1.22073264],
       [1.84407387, 3.63296151, 2.7446576 ]])