# TENSORS A USEFUL DATA STRUCTURE IN PyTorch -

In [1]:
import torch

In [2]:
import numpy as np

In [3]:
#creating a numpy array
data=np.array([1,2,3])

#creating a tensor from "Tensor" constructor and it uses global default datatype as float
data1=torch.Tensor(data)
print(data1)
print(data1.dtype)
#creating a tensor form "tensor" factory function
data2=torch.tensor(data)
print(data2)
print(data2.dtype)

tensor([1., 2., 3.])
torch.float32
tensor([1, 2, 3])
torch.int64


In [4]:
print(data1.dtype)
print(data1.device)
print(data1.layout)

torch.float32
cpu
torch.strided


In [5]:
#we can check default data type for tensor
print(torch.get_default_dtype())

torch.float32


In [6]:
#type inference for factory functions , it checks which data is coming and hence creates a dynamic object based on data type of incoming data
data3=torch.tensor(np.array([1,2,3]))
print(data3.dtype)
data4=torch.tensor(np.array([1.,2.,3.]))
print(data4.dtype)

torch.int64
torch.float64


In [7]:
#explicitly changing datatypes
data5=torch.tensor(np.array([1,2,3]),dtype=torch.float64)
print(data5)

tensor([1., 2., 3.], dtype=torch.float64)


In [8]:
#creating tensors from numpy array by using from_numpy()
#but torch.tensor() can be used almost for everyday.

In [9]:
#different data types can't be operated upon simultaneously 
data6=torch.tensor(np.array([1,2,3]))
data7=torch.tensor(np.array([1.,2.,3.]))
print(data6+data7) #gives error

RuntimeError: Expected object of type torch.LongTensor but found type torch.DoubleTensor for argument #3 'other'

In [10]:
print(torch.eye(2)) #identity tensor by specifying no of rows
print(torch.zeros(2,2)) #rank -2 tensor with two axes with lenght -2
print(torch.randn(2,2)) #random from normal distribution with mean 0 and std deviation1 different from torch.rand() 

tensor([[1., 0.],
        [0., 1.]])
tensor([[0., 0.],
        [0., 0.]])
tensor([[-0.8258,  1.5194],
        [ 0.7441,  2.0127]])


In [11]:
data8=torch.randn(3,4)
print(data8)

tensor([[-0.3768, -0.6888, -0.7030, -0.4510],
        [ 0.4825, -1.6580, -2.1596, -0.0955],
        [ 0.5451, -1.2870,  2.5411,  0.9787]])


In [12]:
#seeing the shape of the tensor as 3 rows and 4 columns with rank-2 tensor with two axes of one of length 3 and other as 4.
data8.shape

torch.Size([3, 4])

In [13]:
#rank of the tensor
len(data8.shape)

2

In [14]:
t=data8
print(t)

tensor([[-0.3768, -0.6888, -0.7030, -0.4510],
        [ 0.4825, -1.6580, -2.1596, -0.0955],
        [ 0.5451, -1.2870,  2.5411,  0.9787]])


In [15]:
#no of elements can be found by product of each of dimensions - 3*4=12
t.numel()

12

In [16]:
#changing the shape of tensor by torch.view() but remeber ! we can't chnage the rank of the tensor and hecne the no of elemetns msut be same in all reshaping
t.view(12,1)

tensor([[-0.3768],
        [-0.6888],
        [-0.7030],
        [-0.4510],
        [ 0.4825],
        [-1.6580],
        [-2.1596],
        [-0.0955],
        [ 0.5451],
        [-1.2870],
        [ 2.5411],
        [ 0.9787]])

In [17]:
t.view(1,12)

tensor([[-0.3768, -0.6888, -0.7030, -0.4510,  0.4825, -1.6580, -2.1596, -0.0955,
          0.5451, -1.2870,  2.5411,  0.9787]])

In [18]:
t.view(6,2)

tensor([[-0.3768, -0.6888],
        [-0.7030, -0.4510],
        [ 0.4825, -1.6580],
        [-2.1596, -0.0955],
        [ 0.5451, -1.2870],
        [ 2.5411,  0.9787]])

In [19]:
#another way of reshaping and rank changed to rank -3 tensor
t.view(3,2,2)

tensor([[[-0.3768, -0.6888],
         [-0.7030, -0.4510]],

        [[ 0.4825, -1.6580],
         [-2.1596, -0.0955]],

        [[ 0.5451, -1.2870],
         [ 2.5411,  0.9787]]])

In [35]:
#flattening the tensor means lower its rank by 1 like here 2-d tensor lowered to 1-d tensor
t=t.squeeze()
print(t)
print(len(t.shape))

tensor([-0.3768, -0.6888, -0.7030, -0.4510,  0.4825, -1.6580, -2.1596, -0.0955,
         0.5451, -1.2870,  2.5411,  0.9787])
1


#operations with dim =1 will be column wise and dim=0 will be row-wise


CNN IMAGE FLATTENING VISUALIZATION - 

In [56]:
#three images with tensors t1,t2,t3 representing pixel values (images 4x4)
t1=torch.tensor([
    [1,1,1,1],
    [1,1,1,1],
    [1,1,1,1],
    [1,1,1,1]
])

t2=torch.tensor([
    [2,2,2,2],
    [2,2,2,2],
    [2,2,2,2],
    [2,2,2,2]
])

t3=torch.tensor([
    [3,3,3,3],
    [3,3,3,3],
    [3,3,3,3],
    [3,3,3,3]
])

#creating a batch of images for representing tensors - > (batch,colorchannel,height,width) for CNN
t=torch.stack((t1,t2,t3))
t=t.view(3,1,4,4)
print(t)

tensor([[[[1, 1, 1, 1],
          [1, 1, 1, 1],
          [1, 1, 1, 1],
          [1, 1, 1, 1]]],


        [[[2, 2, 2, 2],
          [2, 2, 2, 2],
          [2, 2, 2, 2],
          [2, 2, 2, 2]]],


        [[[3, 3, 3, 3],
          [3, 3, 3, 3],
          [3, 3, 3, 3],
          [3, 3, 3, 3]]]])


In [57]:
#inspecting each of the axes of the t tensor for CNN
print(t[0])
print(t[0][0])
print(t[0][0][0])
print(t[0][0][0][0])

tensor([[[1, 1, 1, 1],
         [1, 1, 1, 1],
         [1, 1, 1, 1],
         [1, 1, 1, 1]]])
tensor([[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]])
tensor([1, 1, 1, 1])
tensor(1)


In [63]:
print(t.shape)

torch.Size([3, 16])


In [64]:
t=t.flatten(start_dim=1)
print(t)
print(t.shape)

tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
        [2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
        [3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3]])
torch.Size([3, 16])


# BROADCASTING AND ELEMENT WISE OPERATIONS - 

In [74]:
t1=torch.tensor([
    [1,2],
    [3,4]
    
],dtype=torch.float64)
t2=torch.tensor([
    [5,6],
    [7,8]
],dtype=torch.float64)

print(f"hey i am {t1}")
print(f"hey i am of shape {t1.shape}")
print(f"my rank is {len(t1.shape)}")
print(t2)

hey i am tensor([[1., 2.],
        [3., 4.]], dtype=torch.float64)
hey i am of shape torch.Size([2, 2])
my rank is 2
tensor([[5., 6.],
        [7., 8.]], dtype=torch.float64)


In [75]:
#all arithmetic operations are element wise
print(t1+t2)
print(2*t2)
print(t1/2)

tensor([[ 6.,  8.],
        [10., 12.]], dtype=torch.float64)
tensor([[10., 12.],
        [14., 16.]], dtype=torch.float64)
tensor([[0.5000, 1.0000],
        [1.5000, 2.0000]], dtype=torch.float64)


In [77]:
#how t1+2 is even possible without having same shape can two tensors be operated together ? let's see-
#the lower rank tensor is broadcasted to adjust to the higher rank dimension of tensor , to see this -

np.broadcast_to(2,t1.shape)


array([[2, 2],
       [2, 2]])

In [78]:
t1+2

tensor([[3., 4.],
        [5., 6.]], dtype=torch.float64)

In [79]:
#under the hood broadcasting
t1+ torch.tensor(
np.broadcast_to(2,t1.shape),dtype=torch.float64
)

tensor([[3., 4.],
        [5., 6.]], dtype=torch.float64)

In [86]:
#another example of broadcasting where 2 is broadcasted to [2,2,2]
t3=torch.tensor([1,2,3])
print(t3>2)


tensor([0, 0, 1], dtype=torch.uint8)


In [87]:
#yet another example of broadcasting where lower rank tensor is braocasted to the dimensions of upper rank tensor.
t1=torch.tensor([
    [1,2],
    [3,4]
])
t2=torch.tensor([
    [5,6]
])

print(t1+t2)

tensor([[ 6,  8],
        [ 8, 10]])
