In [0]:
# http://pytorch.org/
from os.path import exists
from wheel.pep425tags import get_abbr_impl, get_impl_ver, get_abi_tag
platform = '{}{}-{}'.format(get_abbr_impl(), get_impl_ver(), get_abi_tag())
cuda_output = !ldconfig -p|grep cudart.so|sed -e 's/.*\.\([0-9]*\)\.\([0-9]*\)$/cu\1\2/'
accelerator = cuda_output[0] if exists('/dev/nvidia0') else 'cpu'

!pip install -q http://download.pytorch.org/whl/{accelerator}/torch-0.4.1-{platform}-linux_x86_64.whl torchvision
import torch

In [0]:
from torch import nn



In [6]:
m=nn.Linear(20,30)
inputs=torch.randn(128,20)
output=m(inputs)
print(m)
print(inputs)
print(inputs.shape)
print(output)
print(output.shape)

Linear(in_features=20, out_features=30, bias=True)
tensor([[-0.9945, -1.6163,  0.7022,  ..., -0.4514, -1.2316,  2.1909],
        [-1.9843,  0.5715,  0.2544,  ...,  0.2894,  0.0535,  0.5636],
        [ 0.7794, -0.7886,  1.2678,  ..., -0.8562, -0.4870, -1.6026],
        ...,
        [ 0.8772,  1.6979,  0.8410,  ...,  0.5235,  0.0081,  0.0923],
        [ 0.3820, -0.9045,  1.3112,  ..., -0.0742,  0.0541, -0.4601],
        [ 0.6215, -1.7491,  2.8087,  ...,  1.9371, -1.8552, -2.3539]])
torch.Size([128, 20])
tensor([[-0.2750,  0.4790,  0.4474,  ..., -1.4150, -0.4036,  0.0721],
        [ 0.4183,  0.5429, -0.4394,  ..., -0.7522, -0.1807, -0.4075],
        [ 0.2177,  1.0904,  0.1214,  ..., -0.3830,  0.5400,  0.2247],
        ...,
        [ 0.6277,  0.0933, -0.5467,  ..., -0.0364, -0.2876, -0.2355],
        [ 0.2444, -0.2164,  0.8922,  ..., -0.0683, -0.3108,  0.6065],
        [ 0.1483,  1.1161,  0.8189,  ...,  0.4444, -0.9471, -0.3768]],
       grad_fn=<ThAddmmBackward>)
torch.Size([128, 30])


In [12]:
sig=nn.Sigmoid()
print(sig)
inputs=torch.randn(2)
print(inputs)
print(inputs.shape)
output=sig(inputs)
print(output)
print(output.shape)


Sigmoid()
tensor([-0.9158, -0.0008])
torch.Size([2])
tensor([0.2858, 0.4998])
torch.Size([2])


In [15]:
somx=nn.Softmax(dim=1)
print(somx)
inputs1=torch.randn(2,3)
print(inputs1)
print(inputs1.shape)
output1=somx(inputs1)
print(output1)
print(output1.shape)


Softmax()
tensor([[-0.1456,  0.7271, -0.4266],
        [ 0.4783,  0.3800,  0.9403]])
torch.Size([2, 3])
tensor([[0.2411, 0.5769, 0.1820],
        [0.2862, 0.2594, 0.4543]])
torch.Size([2, 3])


In [0]:
#using the above to model the neural network

In [0]:
class network(nn.Module):
  
  def __init__(self):
    super().__init__()
    
    self.hidden=nn.Linear(784,256)
    self.output=nn.Linear(256,10)
    self.sig=nn.Sigmoid()
    self.somx=nn.Softmax(dim=1)
  
  def forward_pass(self,x):
    
    x=self.hidden(x)
    x=self.sig(x)
    x=self.output(x)
    x=self.somx(x)
    
    return x  
  

In [19]:
model=network()
print(model)



network(
  (hidden): Linear(in_features=784, out_features=256, bias=True)
  (output): Linear(in_features=256, out_features=10, bias=True)
  (sig): Sigmoid()
  (somx): Softmax()
)
