# Introduction to Tensors

PyTorch tensors are basic data structures replacement for numpy arrays for flexibility and speed.

In [1]:
import torch

In [2]:
#Construct a 5x3 matrix, uninitialized:
x=torch.empty(5,3)
print(x)

tensor([[-4.5931e-37,  4.5900e-41, -4.5931e-37],
        [ 4.5900e-41,  7.1449e+31,  9.1041e-12],
        [ 6.9983e+28,  9.5725e-40,  1.8524e+28],
        [ 6.2608e+22,  4.7428e+30,  1.1096e+27],
        [ 2.7518e+12,  7.5338e+28,  7.5782e+31]])


In [4]:
#creating a tensor from python lists
l=[1,2,3,4,5]
x=torch.tensor(l)
print(x)

tensor([1, 2, 3, 4, 5])


In [5]:
#Construct a randomly initialized matrix:
x=torch.rand(5,3)
print(x)

tensor([[0.3717, 0.8227, 0.8615],
        [0.2906, 0.9239, 0.4888],
        [0.0683, 0.6150, 0.7610],
        [0.4340, 0.5223, 0.9897],
        [0.3097, 0.9726, 0.0254]])


In [10]:
#Construct a matrix filled zeros and of dtype long:
x=torch.zeros(5,3,dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [11]:
x = torch.randn_like(x, dtype=torch.float)    # override dtype!
print(x)           

tensor([[-0.6224,  0.0548, -0.4763],
        [-1.2553, -0.0773,  0.5307],
        [ 0.3632, -2.1453,  0.7655],
        [ 0.0387, -0.5814, -0.4218],
        [-0.0531, -0.1468,  0.3699]])


In [14]:
#creating tensor of numbers chosen from normal distribution whose mean is 0 and std deviation is 1.
x=torch.randn(3,3)
print(x)
y=torch.randn_like(x) #has same shape as x
print(y)

tensor([[ 0.4182, -0.9845,  1.2908],
        [ 0.2575, -1.4836,  2.8398],
        [-1.1411,  0.8935,  1.0237]])
tensor([[ 2.4598,  0.7546, -1.3402],
        [-0.8772, -0.4061,  1.8399],
        [ 1.6120, -2.4337,  1.3197]])


In [16]:
print(x.shape)
print(y.shape)

torch.Size([3, 3])
torch.Size([3, 3])


In [18]:
#adding two tensors
print(x+y)
#or using torch.add(x,y)
print(torch.add(x,y))

tensor([[ 2.8780, -0.2300, -0.0494],
        [-0.6197, -1.8896,  4.6797],
        [ 0.4709, -1.5402,  2.3434]])
tensor([[ 2.8780, -0.2300, -0.0494],
        [-0.6197, -1.8896,  4.6797],
        [ 0.4709, -1.5402,  2.3434]])


In [33]:
x = torch.randn(4, 4)
y = x.view(16)
print(x)
print(y)

tensor([[-0.1256, -0.4845,  0.7244, -0.6450],
        [ 0.3046,  0.2016,  0.4065, -0.0560],
        [-1.1119,  0.5331,  0.9588,  0.0268],
        [-1.7238, -1.3124,  0.4045,  0.2065]])
tensor([-0.1256, -0.4845,  0.7244, -0.6450,  0.3046,  0.2016,  0.4065, -0.0560,
        -1.1119,  0.5331,  0.9588,  0.0268, -1.7238, -1.3124,  0.4045,  0.2065])


In [39]:
z=x.view(1,16)
print(z)
p=x.view(16,1)
print(z)
print(x.shape)
print(y.shape)
print(z.shape)
print(p.shape)

tensor([[-0.1256, -0.4845,  0.7244, -0.6450,  0.3046,  0.2016,  0.4065, -0.0560,
         -1.1119,  0.5331,  0.9588,  0.0268, -1.7238, -1.3124,  0.4045,  0.2065]])
tensor([[-0.1256, -0.4845,  0.7244, -0.6450,  0.3046,  0.2016,  0.4065, -0.0560,
         -1.1119,  0.5331,  0.9588,  0.0268, -1.7238, -1.3124,  0.4045,  0.2065]])
torch.Size([4, 4])
torch.Size([16])
torch.Size([1, 16])
torch.Size([16, 1])


In [40]:
#pytorch automatically calculates required rows if columns are given and vice versa and we specify it by giving it "-1" 
m=x.view(-1,16)
print(m)

tensor([[-0.1256, -0.4845,  0.7244, -0.6450,  0.3046,  0.2016,  0.4065, -0.0560,
         -1.1119,  0.5331,  0.9588,  0.0268, -1.7238, -1.3124,  0.4045,  0.2065]])


In [41]:
l=m.view(-1,4)
print(l)

tensor([[-0.1256, -0.4845,  0.7244, -0.6450],
        [ 0.3046,  0.2016,  0.4065, -0.0560],
        [-1.1119,  0.5331,  0.9588,  0.0268],
        [-1.7238, -1.3124,  0.4045,  0.2065]])


In [42]:
c=x.view(-1,8)
print(c)

tensor([[-0.1256, -0.4845,  0.7244, -0.6450,  0.3046,  0.2016,  0.4065, -0.0560],
        [-1.1119,  0.5331,  0.9588,  0.0268, -1.7238, -1.3124,  0.4045,  0.2065]])


In [59]:
f=torch.randn(5,)
print(f)

tensor([ 1.9283, -0.5242, -0.3831,  1.0091,  0.6448])
